### ISSUE TITLE
Issue using the test-all.py

### ISSUE THREAD

**Issue by smallvalthoss** [nv-tlabs/DIB-R#23]
Looks like there's some files/folders missing in my directory? I am not sure, I'm running on windows 10 and don't know how to format the test command for windows. When I run on bash it seems to not recognize torch.

DIB-R\dib-render>python test-all.py --g_model_dir ./checkpoints/g_model.pth --svfolder ./prediction --data_folder ./dataset --filelist ./test_list.txt
------------------
| Configurations |
------------------

IMG_DIM:         64
N_CHANNELS:      4
BATCH_SIZE:      64
FILELIST:        ./test_list.txt
TOTAL_EPOCH:     1000
ITERS_PER_LOG:   50
VERBOSE:         True

Building dataloaders
./dataset
Traceback (most recent call last):
  File "test-all.py", line 108, in <module>
    bs=BATCH_SIZE, numworkers=numworkers,data_folder=data_folder)
  File "../utils\dataloader\dataloader_multiview_blender.py", line 167, in get_data_loaders
    mode=mode, datadebug=False, classes=classes, data_folder=data_folder)
  File "../utils\dataloader\dataloader_multiview_blender.py", line 53, in __init__
    with open(file_list, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './test_list.txt'

**Comment by 0079zn** [comment]
Mine is also the same problem, there is no tarin.txt folder in the project
